default:
    resource: '@DefaultBundle/Controller/'
    type: annotation
    prefix: /
app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /api
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
api_login_check:
    path: /api/login_check